In [106]:
import pandas as pd
import numpy as np

In [107]:

movies = pd.read_csv("movies_metadata.csv", low_memory=False)
credits = pd.read_csv("credits.csv")
keywords = pd.read_csv("keywords.csv")
ratings = pd.read_csv("ratings_small.csv")

In [108]:
movies.head(2)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0

In [109]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [110]:
movies = movies[movies['id'].str.isnumeric()]
movies['id'] = movies['id'].astype(int)

In [111]:
movies = movies[['id','title','overview','genres']]

In [112]:
movies.head(2)

,id,title,overview,genres
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '..."

In [113]:
credits.head(2)

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844

In [114]:
keywords.head(2)

     id                                           keywords
0   862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1  8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...

In [115]:
credits['id'] = credits['id'].astype(int)
keywords['id'] = keywords['id'].astype(int)

movies = movies.merge(credits, on='id')
movies = movies.merge(keywords, on='id')

In [116]:
movies.head(2)

,id,title,overview,genres,cast,crew,keywords
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1..."

In [117]:
import ast

def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name'])
    return L

movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)

In [118]:
movies.head(2)

,id,title,overview,genres,cast,crew,keywords
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[Animation, Comedy, Family]","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[jealousy, toy, boy, friendship, friends, riva..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[Adventure, Fantasy, Family]","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[board game, disappearance, based on children'..."

In [119]:
def get_cast(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
            counter += 1
    return L

movies['cast'] = movies['cast'].apply(get_cast)

In [120]:
movies.head(2)

,id,title,overview,genres,cast,crew,keywords
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[Animation, Comedy, Family]","[Tom Hanks, Tim Allen, Don Rickles]","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[jealousy, toy, boy, friendship, friends, riva..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[Adventure, Fantasy, Family]","[Robin Williams, Jonathan Hyde, Kirsten Dunst]","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[board game, disappearance, based on children'..."

In [121]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

movies['crew'] = movies['crew'].apply(fetch_director)

In [122]:
movies.head(2)

,id,title,overview,genres,cast,crew,keywords
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[Animation, Comedy, Family]","[Tom Hanks, Tim Allen, Don Rickles]",[John Lasseter],"[jealousy, toy, boy, friendship, friends, riva..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[Adventure, Fantasy, Family]","[Robin Williams, Jonathan Hyde, Kirsten Dunst]",[Joe Johnston],"[board game, disappearance, based on children'..."

In [123]:
movies['overview']

0        Led by Woody, Andy's toys live happily in his ...
1        When siblings Judy and Peter discover an encha...
2        A family wedding reignites the ancient feud be...
3        Cheated on, mistreated and stepped on, the wom...
4        Just when George Banks has recovered from his ...
                               ...
46623          Rising and falling between a man and woman.
46624    An artist struggles to finish his work while a...
46625    When one of her hits goes wrong, a professiona...
46626    In a small town live two brothers, one a minis...
46627    50 years after decriminalisation of homosexual...
Name: overview, Length: 46628, dtype: object

In [124]:
movies.isnull().sum()

id            0
title         4
overview    995
genres        0
cast          0
crew          0
keywords      0
dtype: int64

In [126]:
movies=movies.dropna()

In [127]:
movies.isnull().sum()

id          0
title       0
overview    0
genres      0
cast        0
crew        0
keywords    0
dtype: int64

In [128]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [129]:
movies.head(2)

,id,title,overview,genres,cast,crew,keywords
0,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[Tom Hanks, Tim Allen, Don Rickles]",[John Lasseter],"[jealousy, toy, boy, friendship, friends, riva..."
1,8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a...","[Adventure, Fantasy, Family]","[Robin Williams, Jonathan Hyde, Kirsten Dunst]",[Joe Johnston],"[board game, disappearance, based on children'..."

In [130]:
def collapse(L):
    return [i.replace(" ", "") for i in L]

movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [131]:
movies.head(2)

,id,title,overview,genres,cast,crew,keywords
0,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[TomHanks, TimAllen, DonRickles]",[JohnLasseter],"[jealousy, toy, boy, friendship, friends, riva..."
1,8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a...","[Adventure, Fantasy, Family]","[RobinWilliams, JonathanHyde, KirstenDunst]",[JoeJohnston],"[boardgame, disappearance, basedonchildren'sbo..."

In [132]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [133]:
movies['tags']

0        [Led, by, Woody,, Andy's, toys, live, happily,...
1        [When, siblings, Judy, and, Peter, discover, a...
2        [A, family, wedding, reignites, the, ancient, ...
3        [Cheated, on,, mistreated, and, stepped, on,, ...
4        [Just, when, George, Banks, has, recovered, fr...
                               ...
46623    [Rising, and, falling, between, a, man, and, w...
46624    [An, artist, struggles, to, finish, his, work,...
46625    [When, one, of, her, hits, goes, wrong,, a, pr...
46626    [In, a, small, town, live, two, brothers,, one...
46627    [50, years, after, decriminalisation, of, homo...
Name: tags, Length: 45629, dtype: object

In [134]:
movies['tags'] = movies['tags'].apply(lambda x: " ".join(x))

In [135]:
movies['tags']

0        Led by Woody, Andy's toys live happily in his ...
1        When siblings Judy and Peter discover an encha...
2        A family wedding reignites the ancient feud be...
3        Cheated on, mistreated and stepped on, the wom...
4        Just when George Banks has recovered from his ...
                               ...
46623    Rising and falling between a man and woman. Dr...
46624    An artist struggles to finish his work while a...
46625    When one of her hits goes wrong, a professiona...
46626    In a small town live two brothers, one a minis...
46627    50 years after decriminalisation of homosexual...
Name: tags, Length: 45629, dtype: object

In [136]:
movies = movies.reset_index(drop=True)

In [137]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(movies['tags']).toarray()

In [138]:
from sklearn.neighbors import NearestNeighbors

model = NearestNeighbors(metric='cosine', algorithm='brute')
model.fit(vectors)

NearestNeighbors(algorithm='brute', metric='cosine')

In [139]:
distances, indices = model.kneighbors(vectors[0].reshape(1, -1), n_neighbors=6)

In [140]:
def recommend(movie):
    movie = movie.lower()
    
    if movie not in movies['title'].str.lower().values:
        print("Movie not found!")
        return
    
    index = movies[movies['title'].str.lower() == movie].index[0]

    distances, indices = model.kneighbors(
        vectors[index].reshape(1, -1),
        n_neighbors=6
    )

    for i in indices[0][1:]:
        print(movies.iloc[i].title)

In [146]:
recommend("Jumanji")

Liar Game: Reborn
Table No. 21
Minecraft: The Story of Mojang
Word Wars
Dungeons & Dragons

In [143]:
movies.head(2)

,id,title,overview,genres,cast,crew,keywords,tags
0,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[TomHanks, TimAllen, DonRickles]",[JohnLasseter],"[jealousy, toy, boy, friendship, friends, riva...","Led by Woody, Andy's toys live happily in his ..."
1,8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a...","[Adventure, Fantasy, Family]","[RobinWilliams, JonathanHyde, KirstenDunst]",[JoeJohnston],"[boardgame, disappearance, basedonchildren'sbo...",When siblings Judy and Peter discover an encha...

In [147]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
    return " ".join([ps.stem(i) for i in text.split()])

movies['tags'] = movies['tags'].apply(stem)

In [148]:
movies.head(2)

,id,title,overview,genres,cast,crew,keywords,tags
0,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[TomHanks, TimAllen, DonRickles]",[JohnLasseter],"[jealousy, toy, boy, friendship, friends, riva...","led by woody, andy' toy live happili in hi roo..."
1,8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a...","[Adventure, Fantasy, Family]","[RobinWilliams, JonathanHyde, KirstenDunst]",[JoeJohnston],"[boardgame, disappearance, basedonchildren'sbo...",when sibl judi and peter discov an enchant boa...

In [150]:
import pickle
pickle.dump(movies, open('movies.pkl', 'wb'))
pickle.dump(cv, open('vectorizer.pkl', 'wb'))
pickle.dump(model, open('model.pkl', 'wb'))